Nested Function for Names

In [2]:
def fname(name1):
    def mname(name2):
        def lname(name3):
            return name1+" "+name2+" "+name3
        return lname
    return mname
fullname=fname("Ghulam")
lastname=fullname("Ahmed")
print(lastname("khan"))

Ghulam Ahmed khan


Sum Multiplication Subtraction and Divison of two numbers and also round of to 3 digits

In [4]:
def sum (num1,num2):
    return num1+num2
def sub (num1,num2):
    return num1-num2
def multi (num1,num2):
    return num1*num2
def div_no (num1,num2):
    return round(num1/num2,3) # round function is used for three decimal places
num1=float(input("Enter the first number"))
num2=float(input("Enter the second number"))
print(sum(num1,num2))
print(sub(num1,num2))
print(multi(num1,num2))
print(div_no(num1,num2))

Enter the first number 12
Enter the second number 12


24.0
0.0
144.0
1.0


numpy and pandas are in C++ and we import them as a libaray

# FOR COLLAB WE USE MARK OF EXCLAMATION AND SPACE BEFORE PIP
# ! pip install pandas
# ! pip install numpy

In [53]:
# pip install pandas
# pip install numpy
import numpy as np
import pandas as pd

IN NUMPS WE WORK ON ARRAY DATA

In [55]:
#arange is a function and 12 is aurgument
data=np.arange(12)

Data

In [57]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

To check data type

In [61]:
type(data)

numpy.ndarray

Arrange data 0 to 10

In [213]:
data=np.arange(20)

Check Data

In [65]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
# be carefull reshape is used to form matrix and the numbers are always the product of or the factor of 20 
data=np.arange(20).reshape(2,10)

In [69]:
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [71]:
data=np.arange(24).reshape(4,6)

In [73]:
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [75]:
#It can tell us how many rows and colums.It has four rows and 5 coloms
data.shape

(4, 6)

In [77]:
#Bracket shows the dimension if it has two brackets it is two dimension or if it has three bracket than it has three dimensions
data.ndim

2

In [79]:
#Show numbers from 30 to 60
data1=np.arange(30,60)

In [81]:
data1

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [83]:
#In Reshape aurgument (5,6) is the product of 30
data1=np.arange(30,60).reshape(5,6)

In [85]:
data1

array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

data = np.linspace(20, 10, 5)  # 5 evenly spaced points from 20 to 10
print(data)  # Output: [20.   17.5  15.   12.5  10. ]

In [233]:
data2=np.linspace(20,10,1)

In [235]:
data2

array([20.])

In [229]:
#whenever you want to split data in 2 parts 
data2=np.linspace(20,10,2)


In [231]:
data2

array([20., 10.])

In [225]:
data2=np.linspace(20,10,4)

In [227]:
data2

array([20.        , 16.66666667, 13.33333333, 10.        ])

In [101]:
# It is used for generate a random number every timenew number comes
np.random.randint(10)

3

In [103]:
# It is used for generate a random number
np.random.randint(10)

5

PANDAS (WE ALWAYS WORK ON TABULAR DATA) 

In [105]:
#Column is called series in Pandas 
#Combination series+series = Data frame (It always has indexing)
#Dataframe= rows + column + indexing
#note always write Data D and Frame F Capital letters
#We always represent data frame with df
df=pd.DataFrame(data1)

In [107]:
df

0   1   2   3   4   5
0  30  31  32  33  34  35
1  36  37  38  39  40  41
2  42  43  44  45  46  47
3  48  49  50  51  52  53
4  54  55  56  57  58  59

In [109]:
df=pd.DataFrame(data1,index=["Row1","Row2","Row3","Row4","Row5"],
columns=["column1","column2","column3","column4","column5","column6"])


In [111]:
df

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [113]:
df=pd.DataFrame(data1,columns=["column1","column2","column3","column4","column5","column6"],index=["Row1","Row2","Row3","Row4","Row5"])

In [115]:
df

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

Check the starting 5 rows

In [117]:
df.head()

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

To check the column

In [119]:
df.columns

Index(['column1', 'column2', 'column3', 'column4', 'column5', 'column6'], dtype='object')

To check the shape/Dimensions

In [123]:
df.shape

(5, 6)

In [125]:
df.head()

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

To check the Last Rows

In [127]:
df.tail()

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [129]:
# it is used for to check the sample and every time comes new value
df.sample()

column1  column2  column3  column4  column5  column6
Row3       42       43       44       45       46       47

In [131]:
#three is used for seeing three samples
df.sample(3)

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row5       54       55       56       57       58       59
Row2       36       37       38       39       40       41

In [133]:
#non null value represents that no entry is missed
#key point we have to check the upper entry if the current entry is less than upper and lower and than one entry is missed
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
 4   column5  5 non-null      int32
 5   column6  5 non-null      int32
dtypes: int32(6)
memory usage: 160.0+ bytes


In [135]:
#This can give 1.Count  2.mean  3.standard deviation 4. Minimum 5.25% 6.50% 7.75% 8.Max
# Only numeric data summary is display i-e integer and float .Not string
df.describe()

column1    column2    column3    column4    column5    column6
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000
mean   42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
std     9.486833   9.486833   9.486833   9.486833   9.486833   9.486833
min    30.000000  31.000000  32.000000  33.000000  34.000000  35.000000
25%    36.000000  37.000000  38.000000  39.000000  40.000000  41.000000
50%    42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
75%    48.000000  49.000000  50.000000  51.000000  52.000000  53.000000
max    54.000000  55.000000  56.000000  57.000000  58.000000  59.000000

When you get data sheet that data entry person are not qualified they start some columns with capital letters and some with small letter.
Note your job is to give themnew name as below

In [137]:
df

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

This is used for changing the names of columns

In [139]:
df=pd.DataFrame(data1,index=["Row1","Row2","Row3","Row4","Row5"],
columns=["c1","c2","c3","c4","c5","c6"])

In [141]:
df

c1  c2  c3  c4  c5  c6
Row1  30  31  32  33  34  35
Row2  36  37  38  39  40  41
Row3  42  43  44  45  46  47
Row4  48  49  50  51  52  53
Row5  54  55  56  57  58  59

In [145]:
df=pd.DataFrame(data1,index=["Row1","Row2","Row3","Row4","Row5"],
columns=["column1","column2","column3","column4","column5","column6"])





In [147]:
df

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

#'App': [f'App_{i}' for i in range(1, 31)], This used for (for ) loop f app {1},fapp {2}

In [243]:
# Generating sample of data from Google Play Store data
data = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['0', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}

In [245]:
data

{'App': ['App_1',
  'App_2',
  'App_3',
  'App_4',
  'App_5',
  'App_6',
  'App_7',
  'App_8',
  'App_9',
  'App_10',
  'App_11',
  'App_12',
  'App_13',
  'App_14',
  'App_15',
  'App_16',
  'App_17',
  'App_18',
  'App_19',
  'App_20',
  'App_21',
  'App_22',
  'App_23',
  'App_24',
  'App_25',
  'App_26',
  'App_27',
  'App_28',
  'App_29',
  'App_30'],
 'Category': array(['Education', 'Game', 'Game', 'Education', 'Game', 'Productivity',
        'Game', 'Education', 'Game', 'Health', 'Game', 'Health', 'Health',
        'Productivity', 'Productivity', 'Productivity', 'Health', 'Game',
        'Health', 'Education', 'Health', 'Health', 'Education', 'Health',
        'Game', 'Education', 'Health', 'Education', 'Health', 'Education'],
       dtype='<U12'),
 'Rating': array([1. , 5. , 1.8, 4. , 4.9, 2.7, 1.5, 4.3, 4.5, 3.8, 3.3, 4.2, 2.6,
        2.6, 4.9, 4.1, 1.5, 1.5, 2.5, 1.2, 1.4, 3. , 4.2, 2.5, 2.4, 3.5,
        3.5, 3.8, 3.6, 3.9]),
 'Reviews': array([4573,   90, 1986, 5238, 9028,

In [247]:
#the above data is dictionarybecause we have not done any thing with that
type(data)

dict

In [249]:
#This is used for making Data Frame
df=pd.DataFrame(data)

In [159]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1        Health     2.4     7336                 30M   50,000+  Free   
1    App_2  Productivity     2.2     4113                 30M   10,000+  Free   
2    App_3        Health     3.1     3202  Varies with device    1,000+  Paid   
3    App_4        Health     2.6     8459                 30M   50,000+  Free   
4    App_5     Education     1.9     6523                 30M  100,000+  Free   
5    App_6          Game     4.3     5683                 20M    1,000+  Free   
6    App_7          Game     4.6     8250                 10M  100,000+  Paid   
7    App_8          Game     4.9     6928                 30M    1,000+  Free   
8    App_9          Game     4.4     4333                 10M    1,000+  Free   
9   App_10        Health     3.0     1798                 20M  100,000+  Paid   
10  App_11     Education     1.8     9506  Varies with device   10,000+  Paid   
11  App_12  Productivity     4.5     3639                 30M  100,000+  Paid   
12  App_13          Game     4.2     8602                 30M   10,000+  Free   
13  App_14        Health     4.5     2952                 10M   10,000+  Paid   
14  App_15          Game     4.7     9791                 20M  100,000+  Free   
15  App_16        Health     1.6     2797                 30M  100,000+  Free   
16  App_17  Productivity     2.4     7032  Varies with device    1,000+  Paid   
17  App_18        Health     4.8     4034                 10M  100,000+  Free   
18  App_19        Health     3.3     8763                 10M   10,000+  Paid   
19  App_20     Education     3.3     7147                 20M   50,000+  Paid   
20  App_21     Education     4.7     1263  Varies with device   50,000+  Free   
21  App_22        Health     4.1     6670                 20M    1,000+  Paid   
22  App_23        Health     2.9     7053  Varies with device   50,000+  Paid   
23  App_24          Game     3.1     3027                 30M    1,000+  Free   
24  App_25          Game     4.0     1849                 20M   50,000+  Paid   
25  App_26        Health     2.0     5953  Varies with device  100,000+  Paid   
26  App_27     Education     2.7     1063                 30M  100,000+  Paid   
27  App_28  Productivity     1.8      546  Varies with device   50,000+  Paid   
28  App_29          Game     4.0     1056  Varies with device    1,000+  Paid   
29  App_30        Health     3.2     4431                 20M   50,000+  Paid   

   Price Content Rating  
0      0   Everyone 10+  
1      0       Everyone  
2   4.99       Everyone  
3   0.99     Mature 17+  
4   0.99           Teen  
5      0       Everyone  
6   5.99     Mature 17+  
7   0.99   Everyone 10+  
8      0     Mature 17+  
9   9.99       Everyone  
10  4.99           Teen  
11  1.99       Everyone  
12  5.99           Teen  
13  9.99     Mature 17+  
14  1.99   Everyone 10+  
15  2.99     Mature 17+  
16     0     Mature 17+  
17  4.99           Teen  
18  9.99           Teen  
19  0.99     Mature 17+  
20  0.99       Everyone  
21  9.99           Teen  
22  5.99     Mature 17+  
23  1.99     Mature 17+  
24  0.99   Everyone 10+  
25  1.99   Everyone 10+  
26  5.99   Everyone 10+  
27  2.99           Teen  
28  9.99   Everyone 10+  
29  9.99       Everyone

In [251]:
#First it was Dictionary 
type(data)

dict

In [163]:
# After that it converts to data frame to pandas
type(df)

pandas.core.frame.DataFrame

In Pandas Rows and Colums are called Series

In [165]:
type(df.App)

pandas.core.series.Series

To check first 5 enteries in Data

In [167]:
df.head()

App      Category  Rating  Reviews                Size  Installs  Type  \
0  App_1        Health     2.4     7336                 30M   50,000+  Free   
1  App_2  Productivity     2.2     4113                 30M   10,000+  Free   
2  App_3        Health     3.1     3202  Varies with device    1,000+  Paid   
3  App_4        Health     2.6     8459                 30M   50,000+  Free   
4  App_5     Education     1.9     6523                 30M  100,000+  Free   

  Price Content Rating  
0     0   Everyone 10+  
1     0       Everyone  
2  4.99       Everyone  
3  0.99     Mature 17+  
4  0.99           Teen

In [ ]:
To check Last Entries in Data

In [169]:
df.tail()

App      Category  Rating  Reviews                Size  Installs  Type  \
25  App_26        Health     2.0     5953  Varies with device  100,000+  Paid   
26  App_27     Education     2.7     1063                 30M  100,000+  Paid   
27  App_28  Productivity     1.8      546  Varies with device   50,000+  Paid   
28  App_29          Game     4.0     1056  Varies with device    1,000+  Paid   
29  App_30        Health     3.2     4431                 20M   50,000+  Paid   

   Price Content Rating  
25  1.99   Everyone 10+  
26  5.99   Everyone 10+  
27  2.99           Teen  
28  9.99   Everyone 10+  
29  9.99       Everyone

To check the dimensions of Data

In [171]:
df.shape

(30, 9)

To calculate the mean median of only numeric data not string Data

In [173]:
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.366667  5126.633333
std     1.064581  2795.334641
min     1.600000   546.000000
25%     2.450000  2970.750000
50%     3.250000  5057.000000
75%     4.375000  7123.500000
max     4.900000  9791.000000

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


To check the Random Data Sample

In [177]:
df.sample()

App Category  Rating  Reviews Size  Installs  Type Price Content Rating
17  App_18   Health     4.8     4034  10M  100,000+  Free  4.99           Teen

In [179]:
# Info is used complete information of systems
#The object is string
#Float is one
#Integer is one
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


To check column which is application

In [181]:
df["App"]

0      App_1
1      App_2
2      App_3
3      App_4
4      App_5
5      App_6
6      App_7
7      App_8
8      App_9
9     App_10
10    App_11
11    App_12
12    App_13
13    App_14
14    App_15
15    App_16
16    App_17
17    App_18
18    App_19
19    App_20
20    App_21
21    App_22
22    App_23
23    App_24
24    App_25
25    App_26
26    App_27
27    App_28
28    App_29
29    App_30
Name: App, dtype: object

In [183]:
#To see mutiple columns multiple square bracket is used as it is 2 dimensional
df[["App","Price","Reviews"]]

App Price  Reviews
0    App_1     0     7336
1    App_2     0     4113
2    App_3  4.99     3202
3    App_4  0.99     8459
4    App_5  0.99     6523
5    App_6     0     5683
6    App_7  5.99     8250
7    App_8  0.99     6928
8    App_9     0     4333
9   App_10  9.99     1798
10  App_11  4.99     9506
11  App_12  1.99     3639
12  App_13  5.99     8602
13  App_14  9.99     2952
14  App_15  1.99     9791
15  App_16  2.99     2797
16  App_17     0     7032
17  App_18  4.99     4034
18  App_19  9.99     8763
19  App_20  0.99     7147
20  App_21  0.99     1263
21  App_22  9.99     6670
22  App_23  5.99     7053
23  App_24  1.99     3027
24  App_25  0.99     1849
25  App_26  1.99     5953
26  App_27  5.99     1063
27  App_28  2.99      546
28  App_29  9.99     1056
29  App_30  9.99     4431

In [185]:
#Only described summary is generated numeric data either it is float or integer 
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.366667  5126.633333
std     1.064581  2795.334641
min     1.600000   546.000000
25%     2.450000  2970.750000
50%     3.250000  5057.000000
75%     4.375000  7123.500000
max     4.900000  9791.000000

To check the dimensions

In [187]:
df.shape

(30, 9)

To check the unique entries in Price column

In [189]:
df["Price"].unique()

array(['0', '4.99', '0.99', '5.99', '9.99', '1.99', '2.99'], dtype=object)

To check the unique entries in  Size column

In [191]:
df["Size"].unique()

array(['30M', 'Varies with device', '20M', '10M'], dtype=object)

To check the unique entries in Rating column

In [195]:
# To check the null values and the answere is true and false which is bolean 
df.isnull()

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0   False     False   False    False  False     False  False  False   
1   False     False   False    False  False     False  False  False   
2   False     False   False    False  False     False  False  False   
3   False     False   False    False  False     False  False  False   
4   False     False   False    False  False     False  False  False   
5   False     False   False    False  False     False  False  False   
6   False     False   False    False  False     False  False  False   
7   False     False   False    False  False     False  False  False   
8   False     False   False    False  False     False  False  False   
9   False     False   False    False  False     False  False  False   
10  False     False   False    False  False     False  False  False   
11  False     False   False    False  False     False  False  False   
12  False     False   False    False  False     False  False  False   
13  False     False   False    False  False     False  False  False   
14  False     False   False    False  False     False  False  False   
15  False     False   False    False  False     False  False  False   
16  False     False   False    False  False     False  False  False   
17  False     False   False    False  False     False  False  False   
18  False     False   False    False  False     False  False  False   
19  False     False   False    False  False     False  False  False   
20  False     False   False    False  False     False  False  False   
21  False     False   False    False  False     False  False  False   
22  False     False   False    False  False     False  False  False   
23  False     False   False    False  False     False  False  False   
24  False     False   False    False  False     False  False  False   
25  False     False   False    False  False     False  False  False   
26  False     False   False    False  False     False  False  False   
27  False     False   False    False  False     False  False  False   
28  False     False   False    False  False     False  False  False   
29  False     False   False    False  False     False  False  False   

    Content Rating  
0            False  
1            False  
2            False  
3            False  
4            False  
5            False  
6            False  
7            False  
8            False  
9            False  
10           False  
11           False  
12           False  
13           False  
14           False  
15           False  
16           False  
17           False  
18           False  
19           False  
20           False  
21           False  
22           False  
23           False  
24           False  
25           False  
26           False  
27           False  
28           False  
29           False

To check unique values in Rating column

In [193]:
df["Rating"].unique()

array([2.4, 2.2, 3.1, 2.6, 1.9, 4.3, 4.6, 4.9, 4.4, 3. , 1.8, 4.5, 4.2,
       4.7, 1.6, 4.8, 3.3, 4.1, 2.9, 4. , 2. , 2.7, 3.2])

In [197]:
#sum() is used to check the total null value in table.moreover as their is no null value  in data that is why they are showing 0.If ther is a null value
#if there s null values we have to clean it.This process is cleansing
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

To check the unique entries in price column and Data type

In [199]:
df["Price"].unique()

array(['0', '4.99', '0.99', '5.99', '9.99', '1.99', '2.99'], dtype=object)

In [ ]:
To see the Data entries in price column

In [201]:
df["Price"]

0        0
1        0
2     4.99
3     0.99
4     0.99
5        0
6     5.99
7     0.99
8        0
9     9.99
10    4.99
11    1.99
12    5.99
13    9.99
14    1.99
15    2.99
16       0
17    4.99
18    9.99
19    0.99
20    0.99
21    9.99
22    5.99
23    1.99
24    0.99
25    1.99
26    5.99
27    2.99
28    9.99
29    9.99
Name: Price, dtype: object

In [203]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1        Health     2.4     7336                 30M   50,000+  Free   
1    App_2  Productivity     2.2     4113                 30M   10,000+  Free   
2    App_3        Health     3.1     3202  Varies with device    1,000+  Paid   
3    App_4        Health     2.6     8459                 30M   50,000+  Free   
4    App_5     Education     1.9     6523                 30M  100,000+  Free   
5    App_6          Game     4.3     5683                 20M    1,000+  Free   
6    App_7          Game     4.6     8250                 10M  100,000+  Paid   
7    App_8          Game     4.9     6928                 30M    1,000+  Free   
8    App_9          Game     4.4     4333                 10M    1,000+  Free   
9   App_10        Health     3.0     1798                 20M  100,000+  Paid   
10  App_11     Education     1.8     9506  Varies with device   10,000+  Paid   
11  App_12  Productivity     4.5     3639                 30M  100,000+  Paid   
12  App_13          Game     4.2     8602                 30M   10,000+  Free   
13  App_14        Health     4.5     2952                 10M   10,000+  Paid   
14  App_15          Game     4.7     9791                 20M  100,000+  Free   
15  App_16        Health     1.6     2797                 30M  100,000+  Free   
16  App_17  Productivity     2.4     7032  Varies with device    1,000+  Paid   
17  App_18        Health     4.8     4034                 10M  100,000+  Free   
18  App_19        Health     3.3     8763                 10M   10,000+  Paid   
19  App_20     Education     3.3     7147                 20M   50,000+  Paid   
20  App_21     Education     4.7     1263  Varies with device   50,000+  Free   
21  App_22        Health     4.1     6670                 20M    1,000+  Paid   
22  App_23        Health     2.9     7053  Varies with device   50,000+  Paid   
23  App_24          Game     3.1     3027                 30M    1,000+  Free   
24  App_25          Game     4.0     1849                 20M   50,000+  Paid   
25  App_26        Health     2.0     5953  Varies with device  100,000+  Paid   
26  App_27     Education     2.7     1063                 30M  100,000+  Paid   
27  App_28  Productivity     1.8      546  Varies with device   50,000+  Paid   
28  App_29          Game     4.0     1056  Varies with device    1,000+  Paid   
29  App_30        Health     3.2     4431                 20M   50,000+  Paid   

   Price Content Rating  
0      0   Everyone 10+  
1      0       Everyone  
2   4.99       Everyone  
3   0.99     Mature 17+  
4   0.99           Teen  
5      0       Everyone  
6   5.99     Mature 17+  
7   0.99   Everyone 10+  
8      0     Mature 17+  
9   9.99       Everyone  
10  4.99           Teen  
11  1.99       Everyone  
12  5.99           Teen  
13  9.99     Mature 17+  
14  1.99   Everyone 10+  
15  2.99     Mature 17+  
16     0     Mature 17+  
17  4.99           Teen  
18  9.99           Teen  
19  0.99     Mature 17+  
20  0.99       Everyone  
21  9.99           Teen  
22  5.99     Mature 17+  
23  1.99     Mature 17+  
24  0.99   Everyone 10+  
25  1.99   Everyone 10+  
26  5.99   Everyone 10+  
27  2.99           Teen  
28  9.99   Everyone 10+  
29  9.99       Everyone

Replacing Free with zero .This process is called dat cleansing
df["Price"].replace("Free","0") (If we write this code this will temporary cleaning
and if we write
df["Price"]=df["Price"].replace("Free","0")
This is permanently clean from Google play Data set

In [205]:
df["Price"]=df["Price"].replace("Free","0")

In [207]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1        Health     2.4     7336                 30M   50,000+  Free   
1    App_2  Productivity     2.2     4113                 30M   10,000+  Free   
2    App_3        Health     3.1     3202  Varies with device    1,000+  Paid   
3    App_4        Health     2.6     8459                 30M   50,000+  Free   
4    App_5     Education     1.9     6523                 30M  100,000+  Free   
5    App_6          Game     4.3     5683                 20M    1,000+  Free   
6    App_7          Game     4.6     8250                 10M  100,000+  Paid   
7    App_8          Game     4.9     6928                 30M    1,000+  Free   
8    App_9          Game     4.4     4333                 10M    1,000+  Free   
9   App_10        Health     3.0     1798                 20M  100,000+  Paid   
10  App_11     Education     1.8     9506  Varies with device   10,000+  Paid   
11  App_12  Productivity     4.5     3639                 30M  100,000+  Paid   
12  App_13          Game     4.2     8602                 30M   10,000+  Free   
13  App_14        Health     4.5     2952                 10M   10,000+  Paid   
14  App_15          Game     4.7     9791                 20M  100,000+  Free   
15  App_16        Health     1.6     2797                 30M  100,000+  Free   
16  App_17  Productivity     2.4     7032  Varies with device    1,000+  Paid   
17  App_18        Health     4.8     4034                 10M  100,000+  Free   
18  App_19        Health     3.3     8763                 10M   10,000+  Paid   
19  App_20     Education     3.3     7147                 20M   50,000+  Paid   
20  App_21     Education     4.7     1263  Varies with device   50,000+  Free   
21  App_22        Health     4.1     6670                 20M    1,000+  Paid   
22  App_23        Health     2.9     7053  Varies with device   50,000+  Paid   
23  App_24          Game     3.1     3027                 30M    1,000+  Free   
24  App_25          Game     4.0     1849                 20M   50,000+  Paid   
25  App_26        Health     2.0     5953  Varies with device  100,000+  Paid   
26  App_27     Education     2.7     1063                 30M  100,000+  Paid   
27  App_28  Productivity     1.8      546  Varies with device   50,000+  Paid   
28  App_29          Game     4.0     1056  Varies with device    1,000+  Paid   
29  App_30        Health     3.2     4431                 20M   50,000+  Paid   

   Price Content Rating  
0      0   Everyone 10+  
1      0       Everyone  
2   4.99       Everyone  
3   0.99     Mature 17+  
4   0.99           Teen  
5      0       Everyone  
6   5.99     Mature 17+  
7   0.99   Everyone 10+  
8      0     Mature 17+  
9   9.99       Everyone  
10  4.99           Teen  
11  1.99       Everyone  
12  5.99           Teen  
13  9.99     Mature 17+  
14  1.99   Everyone 10+  
15  2.99     Mature 17+  
16     0     Mature 17+  
17  4.99           Teen  
18  9.99           Teen  
19  0.99     Mature 17+  
20  0.99       Everyone  
21  9.99           Teen  
22  5.99     Mature 17+  
23  1.99     Mature 17+  
24  0.99   Everyone 10+  
25  1.99   Everyone 10+  
26  5.99   Everyone 10+  
27  2.99           Teen  
28  9.99   Everyone 10+  
29  9.99       Everyone

In [209]:
df["Type"]=df["Type"].replace("Free","0")

Now in the Type column Free is replaced with 0

In [211]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1        Health     2.4     7336                 30M   50,000+     0   
1    App_2  Productivity     2.2     4113                 30M   10,000+     0   
2    App_3        Health     3.1     3202  Varies with device    1,000+  Paid   
3    App_4        Health     2.6     8459                 30M   50,000+     0   
4    App_5     Education     1.9     6523                 30M  100,000+     0   
5    App_6          Game     4.3     5683                 20M    1,000+     0   
6    App_7          Game     4.6     8250                 10M  100,000+  Paid   
7    App_8          Game     4.9     6928                 30M    1,000+     0   
8    App_9          Game     4.4     4333                 10M    1,000+     0   
9   App_10        Health     3.0     1798                 20M  100,000+  Paid   
10  App_11     Education     1.8     9506  Varies with device   10,000+  Paid   
11  App_12  Productivity     4.5     3639                 30M  100,000+  Paid   
12  App_13          Game     4.2     8602                 30M   10,000+     0   
13  App_14        Health     4.5     2952                 10M   10,000+  Paid   
14  App_15          Game     4.7     9791                 20M  100,000+     0   
15  App_16        Health     1.6     2797                 30M  100,000+     0   
16  App_17  Productivity     2.4     7032  Varies with device    1,000+  Paid   
17  App_18        Health     4.8     4034                 10M  100,000+     0   
18  App_19        Health     3.3     8763                 10M   10,000+  Paid   
19  App_20     Education     3.3     7147                 20M   50,000+  Paid   
20  App_21     Education     4.7     1263  Varies with device   50,000+     0   
21  App_22        Health     4.1     6670                 20M    1,000+  Paid   
22  App_23        Health     2.9     7053  Varies with device   50,000+  Paid   
23  App_24          Game     3.1     3027                 30M    1,000+     0   
24  App_25          Game     4.0     1849                 20M   50,000+  Paid   
25  App_26        Health     2.0     5953  Varies with device  100,000+  Paid   
26  App_27     Education     2.7     1063                 30M  100,000+  Paid   
27  App_28  Productivity     1.8      546  Varies with device   50,000+  Paid   
28  App_29          Game     4.0     1056  Varies with device    1,000+  Paid   
29  App_30        Health     3.2     4431                 20M   50,000+  Paid   

   Price Content Rating  
0      0   Everyone 10+  
1      0       Everyone  
2   4.99       Everyone  
3   0.99     Mature 17+  
4   0.99           Teen  
5      0       Everyone  
6   5.99     Mature 17+  
7   0.99   Everyone 10+  
8      0     Mature 17+  
9   9.99       Everyone  
10  4.99           Teen  
11  1.99       Everyone  
12  5.99           Teen  
13  9.99     Mature 17+  
14  1.99   Everyone 10+  
15  2.99     Mature 17+  
16     0     Mature 17+  
17  4.99           Teen  
18  9.99           Teen  
19  0.99     Mature 17+  
20  0.99       Everyone  
21  9.99           Teen  
22  5.99     Mature 17+  
23  1.99     Mature 17+  
24  0.99   Everyone 10+  
25  1.99   Everyone 10+  
26  5.99   Everyone 10+  
27  2.99           Teen  
28  9.99   Everyone 10+  
29  9.99       Everyone