In [1]:
def fname(name1):
    def mname(name2):
        def lname(name3):
            return name1+" "+name2+" "+name3
        return lname
    return mname
fullname=fname("Ghulam")
lastname=fullname("Ahmed")
print(lastname("khan"))

Ghulam Ahmed khan


In [11]:
def sum (num1,num2):
    return num1+num2
def sub (num1,num2):
    return num1-num2
def multi (num1,num2):
    return num1*num2
def div_no (num1,num2):
    return round(num1/num2,3) # round function is used for three decimal places
num1=float(input("Enter the first number"))
num2=float(input("Enter the second number"))
print(sum(num1,num2))
print(sub(num1,num2))
print(multi(num1,num2))
print(div_no(num1,num2))

Enter the first number 20
Enter the second number 35


55.0
-15.0
700.0
0.571


In [ ]:
numpy and pandas are in C++ and we import them as a libaray

In [ ]:
# FOR COLLAB WE USE MARK OF EXCLAMATION AND SPACE BEFORE PIP
# ! pip install pandas
# ! pip install numpy

In [11]:
# pip install pandas
# pip install numpy
import numpy as np
import pandas as pd

IN NUMPS WE WORK ON ARRAY DATA

In [17]:
#arange is a function and 12 is aurgument
data=np.arange(12)

In [19]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
type(data)

numpy.ndarray

In [23]:
data=np.arange(20)

In [25]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
# be carefull reshape is used to form matrix and the numbers are always the product of or the factor of 20 
data=np.arange(20).reshape(2,10)

In [29]:
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [33]:
data=np.arange(24).reshape(4,6)

In [35]:
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [37]:
#It can tell us how many rows and colums.It has four rows and 5 coloms
data.shape

(4, 6)

In [39]:
#Bracket shows the dimension if it has two brackets it is two dimension or if it has three bracket than it has three dimensions
data.ndim

2

In [47]:
#Show numbers from 30 to 60
data1=np.arange(30,60)

In [49]:
data1

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [51]:
#In Reshape aurgument (5,6) is the product of 30
data1=np.arange(30,60).reshape(5,6)

In [53]:
data1

array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [67]:
data2=np.linspace(20,10,1)

In [69]:
data2

array([20.])

In [71]:
#whenever you want to split data in 2 parts 
data2=np.linspace(20,10,2)


In [73]:
data2

array([20., 10.])

In [75]:
data2=np.linspace(20,10,4)

In [77]:
data2

array([20.        , 16.66666667, 13.33333333, 10.        ])

In [79]:
# It is used for generate a random number
np.random.randint(10)

3

In [81]:
# It is used for generate a random number
np.random.randint(10)

9

PANDAS (WE ALWAYS WORK ON TABULAR DATA) 

In [83]:
#Column is called series in Pandas 
#Combination series+series = Data frame (It always has indexing)
#Dataframe= rows + column + indexing
#note always write Data D and Frame F Capital letters
#We always represent data frame with df
df=pd.DataFrame(data1)

In [85]:
df

0   1   2   3   4   5
0  30  31  32  33  34  35
1  36  37  38  39  40  41
2  42  43  44  45  46  47
3  48  49  50  51  52  53
4  54  55  56  57  58  59

In [119]:
df=pd.DataFrame(data1,index=["Row1","Row2","Row3","Row4","Row5"],
columns=["column1","column2","column3","column4","column5","column6"])


In [121]:
df

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [127]:
df=pd.DataFrame(data1,columns=["column1","column2","column3","column4","column5","column6"],index=["Row1","Row2","Row3","Row4","Row5"])

In [129]:
df

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [131]:
df.head()

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [137]:
df.columns

Index(['column1', 'column2', 'column3', 'column4', 'column5', 'column6'], dtype='object')

In [139]:
df.shape

(5, 6)

In [141]:
df.head()

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [145]:
df.tail()

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [154]:
# it is used for to check the sample and evry time comes new value
df.sample()

column1  column2  column3  column4  column5  column6
Row2       36       37       38       39       40       41

In [158]:
#three is used for seeing three samples
df.sample(3)

column1  column2  column3  column4  column5  column6
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59
Row1       30       31       32       33       34       35

In [162]:
#non null value represents that no entry is missed
#key point we have to check the upper entry if the current entry is less than upper and lower and than one entry is missed
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
 4   column5  5 non-null      int32
 5   column6  5 non-null      int32
dtypes: int32(6)
memory usage: 160.0+ bytes


In [164]:
#This can give 1.Count  2.mean  3.standard deviation 4. Minimum 5.25% 6.50% 7.75% 8.Max
# Only numeric data summary is display i-e integer and float .Not string
df.describe()

column1    column2    column3    column4    column5    column6
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000
mean   42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
std     9.486833   9.486833   9.486833   9.486833   9.486833   9.486833
min    30.000000  31.000000  32.000000  33.000000  34.000000  35.000000
25%    36.000000  37.000000  38.000000  39.000000  40.000000  41.000000
50%    42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
75%    48.000000  49.000000  50.000000  51.000000  52.000000  53.000000
max    54.000000  55.000000  56.000000  57.000000  58.000000  59.000000

When you get data sheet that data entry person are not qualified they start some columns with capital letters and some with small letter.
Note your job is to give themnew name as below

In [167]:
df

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [169]:
df=pd.DataFrame(data1,index=["Row1","Row2","Row3","Row4","Row5"],
columns=["c1","c2","c3","c4","c5","c6"])

In [171]:
df

c1  c2  c3  c4  c5  c6
Row1  30  31  32  33  34  35
Row2  36  37  38  39  40  41
Row3  42  43  44  45  46  47
Row4  48  49  50  51  52  53
Row5  54  55  56  57  58  59

In [173]:
df=pd.DataFrame(data1,index=["Row1","Row2","Row3","Row4","Row5"],
columns=["column1","column2","column3","column4","column5","column6"])





In [175]:
df

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [ ]:
#'App': [f'App_{i}' for i in range(1, 31)], This used for (for ) loop f app {1},fapp {2}

In [177]:
# Generating sample Google Play Store data
data = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['0', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}

In [179]:
data

{'App': ['App_1',
  'App_2',
  'App_3',
  'App_4',
  'App_5',
  'App_6',
  'App_7',
  'App_8',
  'App_9',
  'App_10',
  'App_11',
  'App_12',
  'App_13',
  'App_14',
  'App_15',
  'App_16',
  'App_17',
  'App_18',
  'App_19',
  'App_20',
  'App_21',
  'App_22',
  'App_23',
  'App_24',
  'App_25',
  'App_26',
  'App_27',
  'App_28',
  'App_29',
  'App_30'],
 'Category': array(['Education', 'Health', 'Health', 'Productivity', 'Education',
        'Health', 'Education', 'Productivity', 'Education', 'Productivity',
        'Education', 'Productivity', 'Health', 'Game', 'Health', 'Health',
        'Health', 'Education', 'Game', 'Game', 'Game', 'Productivity',
        'Productivity', 'Health', 'Health', 'Health', 'Health', 'Game',
        'Productivity', 'Productivity'], dtype='<U12'),
 'Rating': array([4.8, 2.9, 2.3, 3.1, 1.2, 2.5, 4.7, 3.6, 5. , 4.8, 1.8, 1.7, 4.4,
        2. , 2.6, 1.9, 3.1, 3.6, 3.9, 3.8, 4.2, 4.8, 1.6, 1.5, 1.5, 4.9,
        4.5, 1.6, 1.1, 4.5]),
 'Reviews': array([4435

In [181]:
#the above data is dictionarybecause we have not done any thing with that
type(data)

dict

In [187]:
#This is used for making Data Frame
df=pd.DataFrame(data)

In [199]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1     Education     4.8     4435                 20M    1,000+  Free   
1    App_2        Health     2.9     7384                 30M    1,000+  Free   
2    App_3        Health     2.3     6815                 10M    1,000+  Free   
3    App_4  Productivity     3.1     1011                 10M    1,000+  Free   
4    App_5     Education     1.2     1478                 20M    1,000+  Free   
5    App_6        Health     2.5     4808                 20M  100,000+  Free   
6    App_7     Education     4.7     3376  Varies with device   50,000+  Paid   
7    App_8  Productivity     3.6     3413                 20M    1,000+  Free   
8    App_9     Education     5.0     7975                 20M   10,000+  Paid   
9   App_10  Productivity     4.8     9730  Varies with device  100,000+  Paid   
10  App_11     Education     1.8     1203                 20M  100,000+  Free   
11  App_12  Productivity     1.7       17  Varies with device  100,000+  Free   
12  App_13        Health     4.4     7100                 10M    1,000+  Paid   
13  App_14          Game     2.0     7318  Varies with device   10,000+  Paid   
14  App_15        Health     2.6     4007  Varies with device   10,000+  Free   
15  App_16        Health     1.9     7338                 20M  100,000+  Paid   
16  App_17        Health     3.1     7916                 20M   10,000+  Free   
17  App_18     Education     3.6      142                 20M    1,000+  Free   
18  App_19          Game     3.9     1795  Varies with device    1,000+  Free   
19  App_20          Game     3.8     8400                 30M   10,000+  Free   
20  App_21          Game     4.2     9403                 20M   50,000+  Free   
21  App_22  Productivity     4.8     4496                 10M    1,000+  Paid   
22  App_23  Productivity     1.6     7779                 30M    1,000+  Free   
23  App_24        Health     1.5     5607                 10M  100,000+  Free   
24  App_25        Health     1.5     1555  Varies with device   10,000+  Free   
25  App_26        Health     4.9     3632                 10M  100,000+  Free   
26  App_27        Health     4.5     9209                 10M    1,000+  Free   
27  App_28          Game     1.6     9055                 10M    1,000+  Free   
28  App_29  Productivity     1.1     1568                 20M  100,000+  Free   
29  App_30  Productivity     4.5     5666                 10M  100,000+  Paid   

   Price Content Rating  
0      0   Everyone 10+  
1   5.99   Everyone 10+  
2   1.99           Teen  
3   5.99   Everyone 10+  
4   2.99       Everyone  
5   4.99           Teen  
6   5.99           Teen  
7   5.99           Teen  
8   2.99           Teen  
9   5.99       Everyone  
10  5.99     Mature 17+  
11  9.99     Mature 17+  
12  0.99       Everyone  
13  9.99       Everyone  
14     0   Everyone 10+  
15  4.99           Teen  
16  2.99     Mature 17+  
17  0.99   Everyone 10+  
18  9.99           Teen  
19  0.99     Mature 17+  
20  5.99           Teen  
21  4.99       Everyone  
22  9.99           Teen  
23  9.99       Everyone  
24     0   Everyone 10+  
25  0.99       Everyone  
26  1.99           Teen  
27  1.99     Mature 17+  
28  4.99   Everyone 10+  
29  0.99   Everyone 10+

In [193]:
#First it was Dictionary 
type(data)

dict

In [195]:
# After that it converts to data frame pandas
type(df)

pandas.core.frame.DataFrame

In [203]:
type(df.App)

pandas.core.series.Series

In [205]:
df.head()

App      Category  Rating  Reviews Size Installs  Type Price  \
0  App_1     Education     4.8     4435  20M   1,000+  Free     0   
1  App_2        Health     2.9     7384  30M   1,000+  Free  5.99   
2  App_3        Health     2.3     6815  10M   1,000+  Free  1.99   
3  App_4  Productivity     3.1     1011  10M   1,000+  Free  5.99   
4  App_5     Education     1.2     1478  20M   1,000+  Free  2.99   

  Content Rating  
0   Everyone 10+  
1   Everyone 10+  
2           Teen  
3   Everyone 10+  
4       Everyone

In [207]:
df.tail()

App      Category  Rating  Reviews Size  Installs  Type Price  \
25  App_26        Health     4.9     3632  10M  100,000+  Free  0.99   
26  App_27        Health     4.5     9209  10M    1,000+  Free  1.99   
27  App_28          Game     1.6     9055  10M    1,000+  Free  1.99   
28  App_29  Productivity     1.1     1568  20M  100,000+  Free  4.99   
29  App_30  Productivity     4.5     5666  10M  100,000+  Paid  0.99   

   Content Rating  
25       Everyone  
26           Teen  
27     Mature 17+  
28   Everyone 10+  
29   Everyone 10+

In [211]:
df.shape

(30, 9)

In [213]:
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.130000  5121.033333
std     1.330323  3056.144647
min     1.100000    17.000000
25%     1.825000  2190.250000
50%     3.100000  5207.500000
75%     4.475000  7680.250000
max     5.000000  9730.000000

In [215]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


In [217]:
df.sample()

App Category  Rating  Reviews Size Installs  Type Price Content Rating
26  App_27   Health     4.5     9209  10M   1,000+  Free  1.99           Teen

In [219]:
#The object is string
#Float is one
#Integer is one
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


In [223]:
df["App"]

0      App_1
1      App_2
2      App_3
3      App_4
4      App_5
5      App_6
6      App_7
7      App_8
8      App_9
9     App_10
10    App_11
11    App_12
12    App_13
13    App_14
14    App_15
15    App_16
16    App_17
17    App_18
18    App_19
19    App_20
20    App_21
21    App_22
22    App_23
23    App_24
24    App_25
25    App_26
26    App_27
27    App_28
28    App_29
29    App_30
Name: App, dtype: object

In [233]:
#To see mutiple columns multiple square bracket is used as it is 2 dimensional
df[["App","Price","Reviews"]]

App Price  Reviews
0    App_1     0     4435
1    App_2  5.99     7384
2    App_3  1.99     6815
3    App_4  5.99     1011
4    App_5  2.99     1478
5    App_6  4.99     4808
6    App_7  5.99     3376
7    App_8  5.99     3413
8    App_9  2.99     7975
9   App_10  5.99     9730
10  App_11  5.99     1203
11  App_12  9.99       17
12  App_13  0.99     7100
13  App_14  9.99     7318
14  App_15     0     4007
15  App_16  4.99     7338
16  App_17  2.99     7916
17  App_18  0.99      142
18  App_19  9.99     1795
19  App_20  0.99     8400
20  App_21  5.99     9403
21  App_22  4.99     4496
22  App_23  9.99     7779
23  App_24  9.99     5607
24  App_25     0     1555
25  App_26  0.99     3632
26  App_27  1.99     9209
27  App_28  1.99     9055
28  App_29  4.99     1568
29  App_30  0.99     5666

In [235]:
#Only described summary is generated numeric data either it is float or integer 
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.130000  5121.033333
std     1.330323  3056.144647
min     1.100000    17.000000
25%     1.825000  2190.250000
50%     3.100000  5207.500000
75%     4.475000  7680.250000
max     5.000000  9730.000000

In [239]:
df.shape

(30, 9)

In [249]:
df["Price"].unique()

array(['0', '5.99', '1.99', '2.99', '4.99', '9.99', '0.99'], dtype=object)

In [255]:
df["Size"].unique()

array(['20M', '30M', '10M', 'Varies with device'], dtype=object)

In [259]:
df["Rating"].unique()

array([4.8, 2.9, 2.3, 3.1, 1.2, 2.5, 4.7, 3.6, 5. , 1.8, 1.7, 4.4, 2. ,
       2.6, 1.9, 3.9, 3.8, 4.2, 1.6, 1.5, 4.9, 4.5, 1.1])

In [263]:
#boloen answere
df.isnull()

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0   False     False   False    False  False     False  False  False   
1   False     False   False    False  False     False  False  False   
2   False     False   False    False  False     False  False  False   
3   False     False   False    False  False     False  False  False   
4   False     False   False    False  False     False  False  False   
5   False     False   False    False  False     False  False  False   
6   False     False   False    False  False     False  False  False   
7   False     False   False    False  False     False  False  False   
8   False     False   False    False  False     False  False  False   
9   False     False   False    False  False     False  False  False   
10  False     False   False    False  False     False  False  False   
11  False     False   False    False  False     False  False  False   
12  False     False   False    False  False     False  False  False   
13  False     False   False    False  False     False  False  False   
14  False     False   False    False  False     False  False  False   
15  False     False   False    False  False     False  False  False   
16  False     False   False    False  False     False  False  False   
17  False     False   False    False  False     False  False  False   
18  False     False   False    False  False     False  False  False   
19  False     False   False    False  False     False  False  False   
20  False     False   False    False  False     False  False  False   
21  False     False   False    False  False     False  False  False   
22  False     False   False    False  False     False  False  False   
23  False     False   False    False  False     False  False  False   
24  False     False   False    False  False     False  False  False   
25  False     False   False    False  False     False  False  False   
26  False     False   False    False  False     False  False  False   
27  False     False   False    False  False     False  False  False   
28  False     False   False    False  False     False  False  False   
29  False     False   False    False  False     False  False  False   

    Content Rating  
0            False  
1            False  
2            False  
3            False  
4            False  
5            False  
6            False  
7            False  
8            False  
9            False  
10           False  
11           False  
12           False  
13           False  
14           False  
15           False  
16           False  
17           False  
18           False  
19           False  
20           False  
21           False  
22           False  
23           False  
24           False  
25           False  
26           False  
27           False  
28           False  
29           False

In [267]:
#sum() is used to check the total null value in table.moreover as their is no null value in in data that is why they are showing 0
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [269]:
df["Price"].unique()

array(['0', '5.99', '1.99', '2.99', '4.99', '9.99', '0.99'], dtype=object)

In [291]:
df["Price"]

0        0
1     5.99
2     1.99
3     5.99
4     2.99
5     4.99
6     5.99
7     5.99
8     2.99
9     5.99
10    5.99
11    9.99
12    0.99
13    9.99
14       0
15    4.99
16    2.99
17    0.99
18    9.99
19    0.99
20    5.99
21    4.99
22    9.99
23    9.99
24       0
25    0.99
26    1.99
27    1.99
28    4.99
29    0.99
Name: Price, dtype: object

In [309]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1     Education     4.8     4435                 20M    1,000+  Free   
1    App_2        Health     2.9     7384                 30M    1,000+  Free   
2    App_3        Health     2.3     6815                 10M    1,000+  Free   
3    App_4  Productivity     3.1     1011                 10M    1,000+  Free   
4    App_5     Education     1.2     1478                 20M    1,000+  Free   
5    App_6        Health     2.5     4808                 20M  100,000+  Free   
6    App_7     Education     4.7     3376  Varies with device   50,000+  Paid   
7    App_8  Productivity     3.6     3413                 20M    1,000+  Free   
8    App_9     Education     5.0     7975                 20M   10,000+  Paid   
9   App_10  Productivity     4.8     9730  Varies with device  100,000+  Paid   
10  App_11     Education     1.8     1203                 20M  100,000+  Free   
11  App_12  Productivity     1.7       17  Varies with device  100,000+  Free   
12  App_13        Health     4.4     7100                 10M    1,000+  Paid   
13  App_14          Game     2.0     7318  Varies with device   10,000+  Paid   
14  App_15        Health     2.6     4007  Varies with device   10,000+  Free   
15  App_16        Health     1.9     7338                 20M  100,000+  Paid   
16  App_17        Health     3.1     7916                 20M   10,000+  Free   
17  App_18     Education     3.6      142                 20M    1,000+  Free   
18  App_19          Game     3.9     1795  Varies with device    1,000+  Free   
19  App_20          Game     3.8     8400                 30M   10,000+  Free   
20  App_21          Game     4.2     9403                 20M   50,000+  Free   
21  App_22  Productivity     4.8     4496                 10M    1,000+  Paid   
22  App_23  Productivity     1.6     7779                 30M    1,000+  Free   
23  App_24        Health     1.5     5607                 10M  100,000+  Free   
24  App_25        Health     1.5     1555  Varies with device   10,000+  Free   
25  App_26        Health     4.9     3632                 10M  100,000+  Free   
26  App_27        Health     4.5     9209                 10M    1,000+  Free   
27  App_28          Game     1.6     9055                 10M    1,000+  Free   
28  App_29  Productivity     1.1     1568                 20M  100,000+  Free   
29  App_30  Productivity     4.5     5666                 10M  100,000+  Paid   

   Price Content Rating  
0      0   Everyone 10+  
1   5.99   Everyone 10+  
2   1.99           Teen  
3   5.99   Everyone 10+  
4   2.99       Everyone  
5   4.99           Teen  
6   5.99           Teen  
7   5.99           Teen  
8   2.99           Teen  
9   5.99       Everyone  
10  5.99     Mature 17+  
11  9.99     Mature 17+  
12  0.99       Everyone  
13  9.99       Everyone  
14     0   Everyone 10+  
15  4.99           Teen  
16  2.99     Mature 17+  
17  0.99   Everyone 10+  
18  9.99           Teen  
19  0.99     Mature 17+  
20  5.99           Teen  
21  4.99       Everyone  
22  9.99           Teen  
23  9.99       Everyone  
24     0   Everyone 10+  
25  0.99       Everyone  
26  1.99           Teen  
27  1.99     Mature 17+  
28  4.99   Everyone 10+  
29  0.99   Everyone 10+

In [305]:
df["Price"]=df["Price"].replace("Free","0")

In [307]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1     Education     4.8     4435                 20M    1,000+  Free   
1    App_2        Health     2.9     7384                 30M    1,000+  Free   
2    App_3        Health     2.3     6815                 10M    1,000+  Free   
3    App_4  Productivity     3.1     1011                 10M    1,000+  Free   
4    App_5     Education     1.2     1478                 20M    1,000+  Free   
5    App_6        Health     2.5     4808                 20M  100,000+  Free   
6    App_7     Education     4.7     3376  Varies with device   50,000+  Paid   
7    App_8  Productivity     3.6     3413                 20M    1,000+  Free   
8    App_9     Education     5.0     7975                 20M   10,000+  Paid   
9   App_10  Productivity     4.8     9730  Varies with device  100,000+  Paid   
10  App_11     Education     1.8     1203                 20M  100,000+  Free   
11  App_12  Productivity     1.7       17  Varies with device  100,000+  Free   
12  App_13        Health     4.4     7100                 10M    1,000+  Paid   
13  App_14          Game     2.0     7318  Varies with device   10,000+  Paid   
14  App_15        Health     2.6     4007  Varies with device   10,000+  Free   
15  App_16        Health     1.9     7338                 20M  100,000+  Paid   
16  App_17        Health     3.1     7916                 20M   10,000+  Free   
17  App_18     Education     3.6      142                 20M    1,000+  Free   
18  App_19          Game     3.9     1795  Varies with device    1,000+  Free   
19  App_20          Game     3.8     8400                 30M   10,000+  Free   
20  App_21          Game     4.2     9403                 20M   50,000+  Free   
21  App_22  Productivity     4.8     4496                 10M    1,000+  Paid   
22  App_23  Productivity     1.6     7779                 30M    1,000+  Free   
23  App_24        Health     1.5     5607                 10M  100,000+  Free   
24  App_25        Health     1.5     1555  Varies with device   10,000+  Free   
25  App_26        Health     4.9     3632                 10M  100,000+  Free   
26  App_27        Health     4.5     9209                 10M    1,000+  Free   
27  App_28          Game     1.6     9055                 10M    1,000+  Free   
28  App_29  Productivity     1.1     1568                 20M  100,000+  Free   
29  App_30  Productivity     4.5     5666                 10M  100,000+  Paid   

   Price Content Rating  
0      0   Everyone 10+  
1   5.99   Everyone 10+  
2   1.99           Teen  
3   5.99   Everyone 10+  
4   2.99       Everyone  
5   4.99           Teen  
6   5.99           Teen  
7   5.99           Teen  
8   2.99           Teen  
9   5.99       Everyone  
10  5.99     Mature 17+  
11  9.99     Mature 17+  
12  0.99       Everyone  
13  9.99       Everyone  
14     0   Everyone 10+  
15  4.99           Teen  
16  2.99     Mature 17+  
17  0.99   Everyone 10+  
18  9.99           Teen  
19  0.99     Mature 17+  
20  5.99           Teen  
21  4.99       Everyone  
22  9.99           Teen  
23  9.99       Everyone  
24     0   Everyone 10+  
25  0.99       Everyone  
26  1.99           Teen  
27  1.99     Mature 17+  
28  4.99   Everyone 10+  
29  0.99   Everyone 10+

In [331]:
df["Type"]=df["Type"].replace("Free","0")

In [333]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1     Education     4.8     4435                 20M    1,000+     0   
1    App_2        Health     2.9     7384                 30M    1,000+     0   
2    App_3        Health     2.3     6815                 10M    1,000+     0   
3    App_4  Productivity     3.1     1011                 10M    1,000+     0   
4    App_5     Education     1.2     1478                 20M    1,000+     0   
5    App_6        Health     2.5     4808                 20M  100,000+     0   
6    App_7     Education     4.7     3376  Varies with device   50,000+  Paid   
7    App_8  Productivity     3.6     3413                 20M    1,000+     0   
8    App_9     Education     5.0     7975                 20M   10,000+  Paid   
9   App_10  Productivity     4.8     9730  Varies with device  100,000+  Paid   
10  App_11     Education     1.8     1203                 20M  100,000+     0   
11  App_12  Productivity     1.7       17  Varies with device  100,000+     0   
12  App_13        Health     4.4     7100                 10M    1,000+  Paid   
13  App_14          Game     2.0     7318  Varies with device   10,000+  Paid   
14  App_15        Health     2.6     4007  Varies with device   10,000+     0   
15  App_16        Health     1.9     7338                 20M  100,000+  Paid   
16  App_17        Health     3.1     7916                 20M   10,000+     0   
17  App_18     Education     3.6      142                 20M    1,000+     0   
18  App_19          Game     3.9     1795  Varies with device    1,000+     0   
19  App_20          Game     3.8     8400                 30M   10,000+     0   
20  App_21          Game     4.2     9403                 20M   50,000+     0   
21  App_22  Productivity     4.8     4496                 10M    1,000+  Paid   
22  App_23  Productivity     1.6     7779                 30M    1,000+     0   
23  App_24        Health     1.5     5607                 10M  100,000+     0   
24  App_25        Health     1.5     1555  Varies with device   10,000+     0   
25  App_26        Health     4.9     3632                 10M  100,000+     0   
26  App_27        Health     4.5     9209                 10M    1,000+     0   
27  App_28          Game     1.6     9055                 10M    1,000+     0   
28  App_29  Productivity     1.1     1568                 20M  100,000+     0   
29  App_30  Productivity     4.5     5666                 10M  100,000+  Paid   

   Price Content Rating  
0      0   Everyone 10+  
1   5.99   Everyone 10+  
2   1.99           Teen  
3   5.99   Everyone 10+  
4   2.99       Everyone  
5   4.99           Teen  
6   5.99           Teen  
7   5.99           Teen  
8   2.99           Teen  
9   5.99       Everyone  
10  5.99     Mature 17+  
11  9.99     Mature 17+  
12  0.99       Everyone  
13  9.99       Everyone  
14     0   Everyone 10+  
15  4.99           Teen  
16  2.99     Mature 17+  
17  0.99   Everyone 10+  
18  9.99           Teen  
19  0.99     Mature 17+  
20  5.99           Teen  
21  4.99       Everyone  
22  9.99           Teen  
23  9.99       Everyone  
24     0   Everyone 10+  
25  0.99       Everyone  
26  1.99           Teen  
27  1.99     Mature 17+  
28  4.99   Everyone 10+  
29  0.99   Everyone 10+