import numpy as np

In [ ]:
import numpy as np

In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


Check for Dimension

In [21]:
print(arr.ndim)

1


Second Array now its dimension is 2

In [23]:
arr1=np.array([[1,2,3,4],[4,3,5,3]])
print(arr1)
print(arr1.ndim)

[[1 2 3 4]
 [4 3 5 3]]
2


import numpy and pandas from library

In [27]:
import numpy as np
import pandas as pd

In [25]:
data = np.arange(0,20).reshape(5,4)
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


To call data frames pf pandas

In [35]:
df=pd.DataFrame(data,index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2','Column3','Column4'])
print(df)

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19


To see the first 5 Entries it is a function press . and shift to see all functions list

In [37]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

To see the last 5 Entries 

In [39]:
df.tail()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

To see sample of ant three Data

In [43]:
df.sample(3)

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row4       12       13       14       15
Row1        0        1        2        3

To see the columns

In [45]:
df.columns

Index(['Column1', 'Column2', 'Column3', 'Column4'], dtype='object')

To see the information of whole data

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [ ]:
To see the mean and median and percentage of data

In [49]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

To check the Data type

In [51]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In pandas coloumn and rows is called series

In [53]:
print(type(df['Column1']))


<class 'pandas.core.series.Series'>


In [55]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19